### ISSUE TITLE
error help me

### ISSUE THREAD

**Issue by supportts** [gd3kr/BlenderGPT#10]
Traceback (most recent call last):
  File "D:\Download\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\12345\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlenderGPT-main\__init__.py", line 53, in <module>
    import openai
  File "C:\Users\12345\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlenderGPT-main\lib\openai\__init__.py", line 9, in <module>
    from openai.api_resources import (
  File "C:\Users\12345\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlenderGPT-main\lib\openai\api_resources\__init__.py", line 1, in <module>
    from openai.api_resources.audio import Audio  # noqa: F401
  File "C:\Users\12345\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlenderGPT-main\lib\openai\api_resources\audio.py", line 4, in <module>
    from openai import api_requestor, util
  File "C:\Users\12345\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 21, in <module>
    import aiohttp
  File "C:\Users\12345\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlenderGPT-main\lib\aiohttp\__init__.py", line 5, in <module>
    from . import hdrs as hdrs
  File "C:\Users\12345\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\BlenderGPT-main\lib\aiohttp\hdrs.py", line 13, in <module>
    from typing_extensions import Final
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by supportts** [comment]
what i must do? i`m lammer in this

**Comment by gd3kr** [comment]
Hey. Looks like you're on Blender 2.92. The earliest supported version is 3.0.0, I reckon it should install fine on versions above that

**Comment by supportts** [comment]
> Hey. Looks like you're on Blender 2.92. The earliest supported version is 3.0.0, I reckon it should install fine on versions above that

thank you

**Comment by gd3kr** [comment]
closing this thread
