### ISSUE TITLE
I am not a Dev I'm not sure what's happening so I"ll paste the code here. Thank you! 

### ISSUE THREAD

**Issue by 0xgogo** [gd3kr/BlenderGPT#14]
Read prefs: C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
reloading addon: BlenderGPT-main 1679702816.4737766 1679703196.22019 'C:\\Users\\Lucas\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons\\BlenderGPT-main\\__init__.py'
Modules Installed () from 'D:\\BlenderGPT-main.zip' into 'C:\\Users\\Lucas\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons'
Warning: 1 x Draw window and swap: 6.9263 ms, average: 6.92630000 ms
Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\__init__.py", line 91, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\__init__.py", line 236, in execute
    blender_code = generate_blender_code(context.scene.gpt4_chat_input, context.scene.gpt4_chat_history)
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\__init__.py", line 98, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
Error: Python: Traceback (most recent call last):
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\__init__.py", line 91, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Lucas\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

**Comment by AKhilRaghav0** [comment]
The second error is a RateLimitError caused by exceeding the current quota limit for OpenAI API usage. This error is raised by the OpenAI API when trying to create a chat completion. 
This error occurs when the quota limit for the OpenAI API usage has been reached. To resolve this error, either the API usage needs to be reduced, or the account needs to be upgraded to a plan with a higher quota limit.

**Comment by 0xgogo** [comment]
@AKhilRaghav0 , thank you for your response. I have subscribed to GPT Plus, but the error appeared when I wasn't using it. The application functions flawlessly on the website; however, I am uncertain as to why I encounter issues when attempting to use the chat feature in Blender.
