### ISSUE TITLE
Does this require chat gpt-4 access in order to work?

### ISSUE THREAD

**Issue by codyvb** [gd3kr/BlenderGPT#19]
I'm getting this error when I attempt.

`Python: Traceback (most recent call last):
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/__init__.py", line 91, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/__init__.py", line 236, in execute
    blender_code = generate_blender_code(context.scene.gpt4_chat_input, context.scene.gpt4_chat_history)
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/__init__.py", line 98, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/codybrown/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main/lib/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
`

**Comment by AKhilRaghav0** [comment]
It's recommended to install the necessary requirements before proceeding to avoid any potential issues. To do this, I cloned the repository and used pip to install the required packages. After that, I zipped the directory back up and proceeded to install the addon from the preferences menu. Once installed, I entered my own OpenAI API key to authenticate the addon.

**Comment by codyvb** [comment]
hey. I did all of that and installed the add on. this is the error I get when I attempt to use it. are you using chat gpt-3 or gpt-4?

**Comment by gd3kr** [comment]
The addon defaults to GPT3 if you don't have access to GPT4. So it should be fine even if you're not using GPT4

**Comment by Ruuubickk** [comment]
I have GPT-4 access and getting the same error as above regardless.

**Comment by gd3kr** [comment]
@Ruuubickk `openai.error.RateLimitError` suggests that you might not have enough credits to satisfy the API request. Could you make sure you’re not being bottlenecked by your usage limit? https://platform.openai.com/account/billing/limits

**Comment by Ruuubickk** [comment]
I've not made any API calls today, not have I come anywhere close to my soft limit cap!
