### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by RevRelic** [gd3kr/BlenderGPT#29]
Traceback (most recent call last):
  File "E:\3d animation for Blender\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Veeckman\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlenderGPT-main\__init__.py", line 6, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

Whats going on here ( im not shure if i need to have Python set up or whats the problem)

**Comment by gd3kr** [comment]
fixed in latest version. You can re-install it now

**Comment by PastaAldente** [comment]
The newest version allows for the import of openai, but if you select gpt-4, you get the error:

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\__init__.py", line 174, in execute
    blender_code = generate_blender_code(context.scene.gpt4_chat_input, context.scene.gpt4_chat_history, context, system_prompt)
  File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\utilities.py", line 51, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist
```

**Comment by cvanmeurs** [comment]
I am seeing the same as the last post above.  ^  And the execute button just says "please wait", forever.

**Comment by gd3kr** [comment]
Since GPT4 is only available via the waitlist right now, that will happen if you don’t have access yet. https://openai.com/waitlist/gpt-4-api

**Comment by angeltfc** [comment]
^ I have access to GPT4 as well and am getting the same error

**Comment by gd3kr** [comment]
@cvanmeurs unfortunately, yes. While they released access to GPT4 for plus users on ChatGPT, they haven't released it for third-party applications. Those are currently only available via the waitlist.  This sucks because GPT4 generations are much higher quality (albeit slower) than GPT3.5.

**Comment by OrionRandD** [comment]
> The newest version allows for the import of openai, but if you select gpt-4, you get the error:
> 
> ```
> Error: Python: Traceback (most recent call last):
>   File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\__init__.py", line 174, in execute
>     blender_code = generate_blender_code(context.scene.gpt4_chat_input, context.scene.gpt4_chat_history, context, system_prompt)
>   File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\utilities.py", line 51, in generate_blender_code
>     response = openai.ChatCompletion.create(
>   File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_resources\chat_completion.py", line 25, in create
>     return super().create(*args, **kwargs)
>   File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
>     response, _, api_key = requestor.request(
>   File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 226, in request
>     resp, got_stream = self._interpret_response(result, stream)
>   File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 619, in _interpret_response
>     self._interpret_response_line(
>   File "C:\Users\Pasta\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 682, in _interpret_response_line
>     raise self.handle_error_response(
> openai.error.InvalidRequestError: The model: `gpt-4` does not exist
> ```

---------------------------------

I also have got this error...
:(

**Comment by yozshujar** [comment]
same problem No module named 'openai'
