### ISSUE TITLE
Plan and Billing

### ISSUE THREAD

**Issue by enzyme69** [gd3kr/BlenderGPT#3]
Quite possible because I have no Pro account, I cannot make a request.  But there seems like no "free quota" at OpenAI.

```
Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/__init__.py", line 53, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/__init__.py", line 146, in execute
    blender_code = generate_blender_code(self.natural_language_input)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/__init__.py", line 65, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/BlenderGPT-main-2/lib/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

```

**Comment by b03diw** [comment]
I have the same problem as well. have you found the solution ?

**Comment by ahmtcnr** [comment]
Have you find solutions ??

**Comment by raspitakesovertheworld** [comment]
I get this immediately, without having used it at all, which can't be, as I have not been using my quote or anything. Any explaination why this is happening? is this a bug that prevents the plugin from working in the first place?

**Comment by hemanta212** [comment]
You need to replace the line in the `__init__.py` file 
```py
model = "gpt-3.5-turbo"
```
to
```py
model = "text-davinci-003"
```

**Comment by Ruuubickk** [comment]
> You need to replace the line in the `__init__.py` file
> 
> ```python
> model = "gpt-3.5-turbo"
> ```
> 
> to
> 
> ```python
> model = "text-davinci-003"
> ```

That makes no difference on my end.

**Comment by AnthonyAttwood** [comment]
> As the error says : `You exceeded your current quota, please check your plan and billing details.`
> 
> Do you pay for your GPT-4 API? Also, it seems that they have a waitlist now : https://openai.com/waitlist/gpt-4-api

It may sound stupid but can you clarify something for me? I pay for Chat-GPT-4. Is this not the same thing as GPT-4 and having API access? Do I also need to pay for the API access once I'm through the waitlist?

Also, the pro version of this plugin says it lets us use GPT-4 for free through a single payment of 29.99. That's fine but what are the limitations here? Do we have a limit of commands/ prompts per day?
