### ISSUE TITLE
The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by UpsetStarship** [gd3kr/BlenderGPT#36]
I'm getting this error on Blender v3.4.1:

Error: Python: Traceback (most recent call last):
  File "C:\Users\Brian\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\__init__.py", line 174, in execute
    blender_code = generate_blender_code(context.scene.gpt4_chat_input, context.scene.gpt4_chat_history, context, system_prompt)
  File "C:\Users\Brian\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\utilities.py", line 51, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "C:\Users\Brian\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Brian\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Brian\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Brian\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Brian\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

**Comment by hunandy14** [comment]
I have also encountered the same problem. If you manage to solve it, I hope you can update with the follow-up.

**Comment by gd3kr** [comment]
Okay so I think there might be a misunderstanding here. You need to upgrade your account to the paid version from https://platform.openai.com/account/billing/overview for GPT-3.5 (GPT-4 is only available via the [GPT-4 API Waitlist](URL)). ChatGPT plus accounts are not the same and having a ChatGPT Plus account with access to GPT-4 via the web UI will still not give you access to GPT-4 via the API. `openai.error.RateLimitError` will not trigger unless there is something wrong with payments on your OpenAI account.

**Comment by Sladed49** [comment]
I upgraded my account and i'm still getting the same error. Anyone else having the same issue?  "openai. error InvalidRequestError: The model: ' gpt-4' does not exist"

**Comment by Taljansen** [comment]
so it means people who have subscription and use the plus model still cannot use this addon right now (without changing the original code) and have to wait until full access to model 4 is granted?
