### ISSUE TITLE
Troubleshooting : RateLimitError: You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by diazmanne** [gd3kr/BlenderGPT#55]
Python: Traceback (most recent call last):
File "/Users/mannediaz/Library/Application Support/Blender/3.5/scripts/addons/BlenderGPT-main/ init py", line 174, in execute
blender_code = generate_blender_code(context.scene.gpt4_chat input, context.scene.gt4 _chat_ history, context, system_prompt)
File "/Users/mannediaz/Library/Application Support/Blender/3.5/scripts/addons/BlenderGPT-main/utilities.py", line 51, in generate blender code
response = openai. ChatCompletion. create(
File "/Users/mannediaz/Library/Application Support/Blend
<img width="990" alt="Screenshot 2023-06-09 at 17 36 27" src="https://github.com/gd3kr/BlenderGPT/assets/10931032/48f918f1-1570-4fe0-8
<img width="312" alt="Screenshot 2023-06-09 at 17 38 17" src="https://github.com/gd3kr/BlenderGPT/assets/10931032/b4468998-d839-4802-ab3b-e2e31f83cb81">
403-6380f11411cd">
er/3.5/scripts/addons/BlenderGPT-main/lib/openai/api_resources/chat_completion.py", line 25, in create return super).create(*args, **kwargs)
File "/Users/mannediaz/Library/Application Support/Blender/3.5/scripts/addons/BlenderGPT-main/lib/openai/api resources/abstract/engine api resource.py", line 153, in create response,
_, api _key = requestor. request
File "/Users/mannediaz/Library/Application Support/Blender/3.5/scripts/addons/BlenderGPT-main/lib/openai/api requestor. py", line 226, in request
resp, got_ stream = self. _interpret_ response(result, stream)
File "Users/mannediaz/Library/Application Support/Blender/3.5/scripts/addons/BlenderGPT-main/lib/openai/api_requestor.y", line 619, in _interpret_ response self. interpret response line
File "Users/mannediaz/Library/Application Support/Blender/3.5/scripts/addons/BlenderGPT-main/lib/openai/api_requestor.py", line 682, in _interpret response line raise self. handle error response
openai. error. RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by CodyAdam** [comment]
Same issue, I also have GPT-4 subscription

**Comment by ghost** [comment]
Please refer to this: https://github.com/gd3kr/BlenderGPT/issues/57
