### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by alecfilios** [gd3kr/BlenderGPT#57]
I got this error the first time I used the tool. I use Chat GPT 3.5 ( I do not own a payed version) and also Blender 4.0.

Python: Traceback (most recent call last):
  File "...\Blender Foundation\Blender\4.0\scripts\addons\BlenderGPT-main\lib\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "...\Blender Foundation\Blender\4.0\scripts\addons\BlenderGPT-main\lib\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "...\\Blender Foundation\Blender\4.0\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "...\Blender Foundation\Blender\4.0\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "...\Blender Foundation\Blender\4.0\scripts\addons\BlenderGPT-main\lib\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by ghost** [comment]
Hello, 

This error means that you've reached your total amount of free credits provided. It is best to add a credit line for the tokens that you might use. It will only charge you for the quantity used. If you add a credit line, be careful of what Model you use; I am using Chat GPT 3.5 Turbo. I've used a total of 44,000 tokens for just around $0.09 a month with a unit price of $0.000002 a token. However, if you only use a couple prompts a month then there is really no way to charge you for the tokens used. If you can you should definitely think about adding a line of credit! 

Hope this answers your question!
