### ISSUE TITLE
raise ValueError("1-2 args execution context is supported") ValueError:1-2 aras execution context is supported

### ISSUE THREAD

**Issue by ljrirene** [gd3kr/BlenderGPT#59]
Report: Error
Python: Traceback (most recent call last):
File "/Users/ljiarong/Library/Application Support/Blender/4.0/scripts/addons/BlenderGpT-main/_init_.py", ine 94, in executetext editor area = split area to text editor(context)
File "/Users/llaronallibrarvlApplication Suoport/Blender/4 0lscriptsladdons/BlenderGPT-main/utilities py". line 85. in split area to text editobpy.ops.screen.area_split(override, direction="VERTICAL' factor=0.5)
File "/Applications/Blender.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py", line 106, in _call
C exec,C undo= BPyOpsSubModOp._parse_args(args)
File "/Applications/Blender.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py", line 60, in _parse_args
raise ValueError("1-2 args execution context is supported")
ValueError:1-2 aras execution context is supported

Hi, every time when I'm trying to build something, I get this error. But I can still get the 3D result here. Does anyone know how to fix this?

**Comment by elliotrpage** [comment]
I am also getting this, using Blender 4.2.0 and the latest Plugin.
Using GPT-3.5 Turbo.

**Comment by Leele1968** [comment]
I meet the same problem, tried to use gpt-3.5 and something else way but not work
