### ISSUE TITLE
what wrong  ?

### ISSUE THREAD

**Issue by minanapil13** [gd3kr/BlenderGPT#68]
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGPT-main\__init__.py", line 174, in execute
    blender_code = generate_blender_code(context.scene.gpt4_chat_input, context.scene.gpt4_chat_history, context, system_prompt)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGPT-main\utilities.py", line 51, in generate_blender_code
    response = openai.ChatCompletion.create(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\openai\lib\_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by prabhtheone** [comment]
The error occurs because the installed openai Python package in Blender is version 1.0.0 or higher, which introduced breaking API changes and removed openai.ChatCompletion.create().

To resolve this issue, you can either downgrade the openai package inside Blender's Python environment or update the addon code.

Solution 1: Downgrade the OpenAI Package (Easiest)

Install the older version of the library into Blender's bundled Python executable.

Close Blender.

Open Command Prompt as Administrator.

Run the following command to downgrade openai using Blender's Python binary:

DOS
"C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\bin\python.exe" -m pip install openai==0.28.1
Restart Blender and try running the addon again.

Solution 2: Update the Addon Code to OpenAI v1.0+

If you want to keep the newer openai library version, update utilities.py in the addon folder:

Open `C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlenderGPT-main
