### ISSUE TITLE
No module named 'openai.object_classes'

### ISSUE THREAD

**Issue by melontoucan** [gd3kr/BlenderGPT#9]
Python: Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\__init__.py", line 174, in execute
    blender_code = generate_blender_code(self.natural_language_input)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT-main\__init__.py", line 109, in generate_blender_code
    for event in response:
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT\lib\openai\api_resources\abstract\engine_api_resource.py", line 167, in <genexpr>
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT\lib\openai\util.py", line 132, in convert_to_openai_object
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlenderGPT\lib\openai\util.py", line 96, in get_object_classes
ModuleNotFoundError: No module named 'openai.object_classes'

**Comment by gd3kr** [comment]
Are you sure you're on a Blender version after 3.0.0?

**Comment by melontoucan** [comment]
Yep 3.4

**Comment by prnthh** [comment]
+1, got this right after installing on mac os

**Comment by shubhankg-nd** [comment]
Facing same issue in jupyter notebook and macos
`No module named 'openai.object_classes`

**Comment by cristal2431** [comment]
Is here any update? I am getting the same issue in my google colab
`No module named 'openai.object_classes`

**Comment by abhishekmishramm1997** [comment]
Hi, i was facing the same issue. I downgraded openai by `pip install openai==0.28`. That seemed to have fixed the issue. For now.

**Comment by hanxu49** [comment]
Use the old version, such as 0.28.1!
